In [1]:
import numpy as np
# Wang's Reading
# MIC format: M*8 [loc,euler(rad),off,dri], mic1 params all zero
MIC = np.load("Simulation_dataset/0_SETTING/MIC_CONFIG.npy")
mic_location_gt = MIC[[0,1,4,6,7], :3]
mic_angle_gt = MIC[[0,1,4,6,7],3:6]/np.pi*180
mic_asyn_gt = MIC[[0,1,4,6,7],6:8]
# s_k_real format: K*3
s_k_real = np.load("Simulation_dataset/0_SETTING/pattern_{}_src.npy".format(1))
mic_asyn_gt
# print(np.round(MIC,3))
# print(np.round(s_k_real,3))

array([[0.00000000e+00, 0.00000000e+00],
       [2.36048090e-02, 1.03166034e-05],
       [9.17955043e-02, 8.00452351e-05],
       [5.36680008e-02, 2.76682643e-05],
       [1.72664529e-02, 1.06183292e-05]])

In [54]:
# Our Reading
import scipy.io as sio
from scipy.spatial.transform import Rotation

# 读取 MATLAB 文件
mat_data = sio.loadmat('zhangSimDataset/g_list.mat')
# 获取结构体数据
g_list=mat_data['g_list']
g=g_list[0]
M=g['M'][0][0][0]
K=g['K'][0][0][0]
x_gt=g['x_gt'][0]

mic_location_gt=x_gt[0:M,0:3]

mic_angle_gt=[]
mic_lie_a_gt=x_gt[0:M,3:6]
for mic_lie_a in mic_lie_a_gt:
    rot = Rotation.from_rotvec(mic_lie_a)
    euler_angles = rot.as_euler('xyz', degrees=True) # zyx?
    mic_angle_gt.append(euler_angles)
mic_angle_gt=np.array(mic_angle_gt)

mic_asyn_gt=x_gt[0:M,6:8]
mic_asyn_gt[:,1]=np.array([dri-mic_asyn_gt[0,1] for dri in mic_asyn_gt[:,1]])

s_k_real=x_gt[M+1:,0:3]

record_time=g['dt'][0].T
record_time=record_time[0]
record_time
# mic_location_gt[1:M,:]
# np.round(g['x'],3)

array([0.        , 5.17823228, 4.60404594, 8.90997102, 3.22626365,
       9.74847468, 8.40593221, 0.49817092])

In [4]:
# Our Reading
import scipy.io as sio
from scipy.spatial.transform import Rotation

# 读取 MATLAB 文件
mat_data = sio.loadmat('zhangSimDataset/g_list0.mat')
# 获取结构体数据
g_list=mat_data['g_list']
g=g_list[0]
M=g['M'][0][0][0]
K=g['K'][0][0][0]
x_gt=g['x_gt'][0]

mic_location_gt=x_gt[0:M,0:3]

mic_angle_gt=[]
mic_lie_a_gt=x_gt[0:M,3:6]
for mic_lie_a in mic_lie_a_gt:
    rot = Rotation.from_rotvec(mic_lie_a)
    euler_angles = rot.as_euler('xyz', degrees=True) # zyx?
    mic_angle_gt.append(euler_angles)
mic_angle_gt=np.array(mic_angle_gt)

mic_asyn_gt=x_gt[0:M,6:8]
mic_asyn_gt[:,1]=np.array([dri-mic_asyn_gt[0,1] for dri in mic_asyn_gt[:,1]])

s_k_real=x_gt[M+1:,0:3]

record_time=g['dt'][0].T
record_time=record_time[0]
# mic_location_gt[1:M,:]
# np.round(g['x'],3)

# TDOA DOA Odo
# su_tdoa=g['su_tdoa'][0].T
# su_tdoa=np.hstack((np.zeros((K,1)),su_tdoa))
# su_tdoa

doa=g['doa'][0]
wangDoa=[]
for j in range(K):
    wangDoa.append(doa[M*j:M*(j+1),:])
doa=np.array(wangDoa)
doa.shape

odo=g['S'][0].T
odo=np.vstack((odo,np.zeros((1,3))))
np.vstack((g['S'][0].T,np.zeros((1,3))))

record_time=g['dt'][0].T
record_time=record_time[0]
record_time

array([0.        , 5.84213736, 8.36561663, 9.4813382 , 5.04643198,
       3.63830334, 8.43377317, 8.909844  ])

In [2]:
pattern=1
# tdoa_mea format: K-1*M
tdoa_mea  = np.load("Simulation_dataset/1_TDOA/pattern_{}_measurement.npy".format(pattern))
tdoa_ture = np.load("Simulation_dataset/1_TDOA/pattern_{}_true.npy".format(pattern))
# doa_mea format: K*M*3
doa_mea = np.load("Simulation_dataset/2_DOA/pattern_{}_measurement.npy".format(pattern))
doa_ture = np.load("Simulation_dataset/2_DOA/pattern_{}_ture.npy".format(pattern))
# odo_mea format: K*3, last row is zero vec.
odo_mea = np.load("Simulation_dataset/3_ODO/pattern_{}_measurement.npy".format(pattern))
odo_ture = np.load("Simulation_dataset/3_ODO/pattern_{}_ture.npy".format(pattern))
# print(tdoa_mea)
# print(doa_mea.shape)
print(odo_mea)

[[-0.34268684  0.02187012  0.00653462]
 [-0.02697275 -0.07460342 -0.30593579]
 [ 0.03381191 -0.0454228  -0.2841546 ]
 [ 0.32043653  0.07893842  0.01805467]
 [-0.34340978  0.03713214  0.00333385]
 [ 0.00387454  0.00228383  0.32867949]
 [ 0.01902676  0.02431965  0.34397759]
 [ 0.05437771 -0.04069427 -0.34724229]
 [ 0.02473962  0.29804039  0.04693469]
 [ 0.02138115 -0.0054302   0.34935932]
 [-0.01759839 -0.0444556   0.35905076]
 [-0.30504036  0.00343324 -0.0006587 ]
 [-0.06381434 -0.35836556 -0.01396525]
 [ 0.00701132  0.04155106 -0.34892215]
 [-0.02340456  0.02866829 -0.33713542]
 [-0.04105838 -0.29677891 -0.02572504]
 [-0.01684413 -0.36433893  0.01076313]
 [ 0.36554377 -0.01126514  0.01189103]
 [-0.34747672  0.07009823  0.04508357]
 [-0.01786379  0.01585023  0.36152808]
 [ 0.01278856  0.31058862 -0.00487101]
 [-0.31152903  0.01332249 -0.02570468]
 [ 0.01340785 -0.36377277 -0.0639697 ]
 [ 0.00521589  0.02853604  0.34659025]
 [ 0.04407052  0.05248549  0.34393925]
 [-0.01930012  0.33191622

In [92]:
from scipy.io import loadmat
sound_event = loadmat(r"Real_world_dataset/exp2/the pattern " + str(1) + " sound seq.mat")["seq_time"]
time_step = np.zeros(len(sound_event)-1)
for i in range(len(sound_event)-1):
    current_time = sound_event[i+1,1] + sound_event[i+1, 2] / 1e9
    start_time = sound_event[0,1] + sound_event[0,2] / 1e9
    time_step[i] = current_time -start_time
time_step

array([ 1.05002403,  4.2500391 ,  7.64995193, 13.65002704, 16.94998407,
       22.75001812, 26.15002608, 31.80082011, 35.19992399, 42.05007601,
       45.35013509, 52.04990911, 55.39986706])

In [8]:
zhangDataset = sio.loadmat(f"zhangSimDataset/g_list0.mat")
g_list=zhangDataset['g_list']
g=g_list[0,0]
odo_mea=g['S'].T
odo_mea2=np.vstack((odo_mea[1:,:],odo_mea[-1,:]))
print(odo_mea)
odo_mea=odo_mea2-odo_mea
odo_mea

[[1.00868816 1.02181484 1.00555014]
 [4.04888292 1.00451981 0.99934355]
 [4.02115824 4.01121607 0.99257533]
 [1.04282422 3.96428302 0.95932701]
 [1.07082197 3.99852693 4.01831679]
 [1.04393078 0.97010829 4.06210125]
 [4.04287258 0.96235543 4.08986855]
 [4.04637437 3.99320278 4.11984714]]


array([[ 3.04019476, -0.01729503, -0.00620659],
       [-0.02772468,  3.00669626, -0.00676822],
       [-2.97833402, -0.04693305, -0.03324832],
       [ 0.02799775,  0.0342439 ,  3.05898977],
       [-0.02689119, -3.02841863,  0.04378447],
       [ 2.9989418 , -0.00775287,  0.0277673 ],
       [ 0.00350179,  3.03084735,  0.02997859],
       [ 0.        ,  0.        ,  0.        ]])